const crypto = require('crypto');
const Appointment = require('../models/Appointment');
const Prescription = require('../models/Prescription');
const LabTest = require('../models/LabTest');
const Doctor = require('../models/Doctor');
const Patient = require('../models/Patient');
const User = require('../models/User');
const Notification = require('../models/Notification');
const MedicineCatalog = require('../models/MedicineCatalog');
const MedicineMapping = require('../models/MedicineMapping');
const { generatePrescriptionPDF } = require('../services/prescriptionPdfService');
const aiService = require('../services/aiService');
const geminiService = require('../services/geminiService');
const { extractTextFromPDF } = require('../services/pdfService');
const path = require('path');
const fs = require('fs');

// @desc    Get smart medicine recommendations (rule-based + AI fallback)
// @route   POST /api/doctor/smart-recommendations
// @access  Private/Doctor
exports.getSmartRecommendations = async (req, res) => {
    try {
        const { diseaseName, diseaseType, severity, symptoms } = req.body;

        if (!diseaseName) {
            return res.status(400).json({ message: 'Disease name is required for recommendations' });
        }

        // 1. Try rule-based mapping first
        let mapping = await MedicineMapping.findOne({
            diseaseName: { $regex: new RegExp(`^${diseaseName}$`, 'i') },
            $or: [
                { diseaseType: { $regex: new RegExp(`^${diseaseType}$`, 'i') } },
                { diseaseType: '' },
                { diseaseType: null }
            ],
            $or: [
                { severity: severity },
                { severity: 'All' }
            ]
        }).sort({ severity: -1, diseaseType: -1 }); // Prioritize specific matches

        if (mapping && mapping.suggestedMedicines && mapping.suggestedMedicines.length > 0) {
            return res.json({
                source: 'rule-based',
                recommendations: mapping.suggestedMedicines,
                notes: mapping.notes
            });
        }

        // 2. Fallback to AI if no rule-based mapping is found
        try {
            const aiSuggestions = await geminiService.getMedicineRecommendations({
                diseaseName,
                diseaseType,
                severity,
                symptoms
            });

            return res.json({
                source: 'AI',
                recommendations: aiSuggestions.recommendations || [],
                cautionNotes: aiSuggestions.cautionNotes || '',
                notes: 'Generated by AI based on symptoms and diagnosis.'
            });
        } catch (aiError) {
            console.error('AI Recommendation Error:', aiError);
            return res.json({
                source: 'none',
                recommendations: [],
                message: 'No recommendations found and AI assistant is currently unavailable.'
            });
        }
    } catch (error) {
        console.error(error);
        res.status(500).json({ message: 'Server error', error: error.message });
    }
};

// @desc    Get doctor's appointments
// @route   GET /api/doctor/appointments
// @access  Private/Doctor
exports.getAppointments = async (req, res) => {
    try {
        const doctor = await Doctor.findOne({ userId: req.user._id });

        if (!doctor) {
            return res.status(404).json({ message: 'Doctor profile not found' });
        }

        const { date } = req.query;
        let query = { doctorId: doctor._id };

        if (date) {
            const startDate = new Date(date);
            startDate.setHours(0, 0, 0, 0);
            const endDate = new Date(date);
            endDate.setHours(23, 59, 59, 999);
            query.appointmentDate = { $gte: startDate, $lte: endDate };
        }

        const appointments = await Appointment.find(query)
            .populate('patientId', 'fullName age gender mobile')
            .sort({ appointmentDate: 1, timeSlot: 1 });

        res.json(appointments);
    } catch (error) {
        console.error(error);
        res.status(500).json({ message: 'Server error' });
    }
};

// @desc    Get doctor's upcoming appointments (next N days)
// @route   GET /api/doctor/appointments/upcoming
// @access  Private/Doctor
exports.getUpcomingAppointments = async (req, res) => {
    try {
        const doctor = await Doctor.findOne({ userId: req.user._id });
        if (!doctor) {
            return res.status(404).json({ message: 'Doctor profile not found' });
        }

        const days = Math.min(parseInt(req.query.days) || 7, 14);
        const start = new Date();
        start.setHours(0, 0, 0, 0);
        const end = new Date(start);
        end.setDate(end.getDate() + days);
        end.setHours(23, 59, 59, 999);

        const appointments = await Appointment.find({
            doctorId: doctor._id,
            appointmentDate: { $gte: start, $lte: end },
            status: { $in: ['scheduled', 'in-progress'] }
        })
            .populate('patientId', 'fullName age gender mobile')
            .sort({ appointmentDate: 1, slotStartTime: 1 });

        res.json(appointments);
    } catch (error) {
        console.error(error);
        res.status(500).json({ message: 'Server error' });
    }
};

// @desc    Get patient EMR (optionally filtered to one family member)
// @route   GET /api/doctor/patient/:id?memberId=<id|null>
// @access  Private/Doctor
exports.getPatientEMR = async (req, res) => {
    try {
        const patient = await Patient.findById(req.params.id);

        if (!patient) {
            return res.status(404).json({ message: 'Patient not found' });
        }

        // memberId query param:
        //   'null' or absent → main account holder (bookedForMember.memberId is null)
        //   '<mongoId>'      → specific family member
        const { memberId } = req.query;
        const isFiltered = memberId !== undefined; // caller explicitly passed the param

        let memberFilter = {};
        if (isFiltered) {
            const idValue = memberId === 'null' || memberId === '' ? null : memberId;
            memberFilter = { 'bookedForMember.memberId': idValue };
        }

        // If filtering, also surface the matching family member's info from the patient doc
        let memberInfo = null;
        if (isFiltered && memberId && memberId !== 'null') {
            memberInfo = patient.familyMembers?.id(memberId) || null;
        }

        const baseQuery = { patientId: patient._id, ...memberFilter };

        const prescriptions = await Prescription.find(baseQuery)
            .populate('doctorId', 'fullName specialization')
            .sort({ createdAt: -1 })
            .limit(20);

        const labTests = await LabTest.find(baseQuery)
            .sort({ createdAt: -1 })
            .limit(20);

        const appointments = await Appointment.find(baseQuery)
            .populate('doctorId', 'fullName specialization')
            .sort({ appointmentDate: -1 })
            .limit(20);

        res.json({
            patient,
            memberInfo,  // null for main account, sub-doc for family member
            prescriptions,
            labTests,
            appointments
        });
    } catch (error) {
        console.error(error);
        res.status(500).json({ message: 'Server error' });
    }
};

// @desc    Create prescription (with digital signature & PDF generation)
// @route   POST /api/doctor/prescription
// @access  Private/Doctor
exports.createPrescription = async (req, res) => {
    try {
        const doctor = await Doctor.findOne({ userId: req.user._id });

        if (!doctor) {
            return res.status(404).json({ message: 'Doctor profile not found' });
        }

        const { patientId, appointmentId, diagnosis, medicines, labTestsRequested, notes } = req.body;

        // ── Resolve who this prescription is for ────────────────────────────
        // If the appointment ID is provided, pull bookedForMember from it so
        // prescriptions and lab tests automatically inherit the correct person.
        let bookedForMember = null;
        if (appointmentId) {
            const apt = await Appointment.findById(appointmentId)
                .select('bookedForMember').lean();
            if (apt?.bookedForMember?.memberId) {
                bookedForMember = apt.bookedForMember;
            }
        }

        const displayName = bookedForMember?.memberName
            ? `${bookedForMember.memberName} (${bookedForMember.relation})`
            : null; // will fall back to patient full name in notification

        const prescription = await Prescription.create({
            patientId,
            doctorId: doctor._id,
            appointmentId,
            bookedForMember,
            diagnosis,
            medicines,
            labTestsRequested,
            notes
        });

        // Add: Automatically create Laboratory test requests and notify lab department
        if (labTestsRequested && labTestsRequested.length > 0) {
            try {
                const labRequests = labTestsRequested.map(test => ({
                    patientId,
                    doctorId: doctor._id,
                    bookedForMember,  // ← inherit from appointment
                    testName: test.name,
                    description: `Automatically requested via Prescription #${prescription.prescriptionId}`,
                    status: 'requested'
                }));
                const created = await LabTest.insertMany(labRequests);
                const labUsers = await User.find({ role: 'laboratory', status: 'approved' }).select('_id').lean();
                const patientForLab = await Patient.findById(patientId).select('fullName').lean();
                const pName = displayName || patientForLab?.fullName || 'Patient';
                for (const u of labUsers) {
                    await Notification.create({
                        userId: u._id,
                        type: 'lab_request',
                        title: 'New Lab Test Request (from Prescription)',
                        message: `Dr. ${doctor.fullName} requested ${labTestsRequested.map(t => t.name).join(', ')} for ${pName}.`,
                        data: { labTestId: created[0]?._id, prescriptionId: prescription._id }
                    });
                }
                console.log(`🧪 Created ${labRequests.length} Laboratory requests from prescription`);
            } catch (labError) {
                console.error('Failed to create LabTest records:', labError);
                // We don't throw here to avoid failing the prescription issuance
            }
        }

        // Increment prescribeCount for each medicine to track popularity
        if (medicines && medicines.length > 0) {
            try {
                const medicineIds = medicines
                    .filter(m => m.medicineId)
                    .map(m => m.medicineId);

                if (medicineIds.length > 0) {
                    await MedicineCatalog.updateMany(
                        { _id: { $in: medicineIds } },
                        { $inc: { prescribeCount: 1 } }
                    );
                    console.log(`📈 Incremented popularity for ${medicineIds.length} medicines`);
                }
            } catch (incError) {
                console.error('Error incrementing medicine popularity:', incError);
                // Don't fail the prescription creation if this fails
            }
        }

        // Generate digital signature (hash of prescriptionId + doctorId + timestamp)
        const signPayload = `${prescription.prescriptionId}-${doctor._id}-${Date.now()}`;
        const digitalSignature = crypto.createHash('sha256').update(signPayload).digest('hex').slice(0, 32).toUpperCase();

        prescription.digitalSignature = digitalSignature;
        prescription.signedAt = new Date();
        await prescription.save();

        // Generate PDF
        const patient = await Patient.findById(patientId);
        if (patient) {
            const { relativePath } = await generatePrescriptionPDF(prescription, doctor, patient);
            prescription.pdfPath = relativePath;
            await prescription.save();
        }

        // Update appointment status if provided
        if (appointmentId) {
            await Appointment.findByIdAndUpdate(appointmentId, { status: 'completed' });
        }

        // Notify patient: prescription available on dashboard
        const patientForNotif = await Patient.findById(patientId).select('userId fullName').lean();
        if (patientForNotif?.userId) {
            const forWhom = displayName || patientForNotif.fullName || 'you';
            await Notification.create({
                userId: patientForNotif.userId,
                type: 'prescription',
                title: 'New Prescription',
                message: `A new prescription from Dr. ${doctor.fullName} for ${forWhom} is available in your dashboard.`,
                data: { prescriptionId: prescription._id }
            });
        }

        const populated = await Prescription.findById(prescription._id)
            .populate('patientId', 'fullName age gender mobile')
            .populate('doctorId', 'fullName specialization department');

        res.status(201).json(populated);
    } catch (error) {
        console.error('❌ CREATE PRESCRIPTION ERROR:', {
            message: error.message,
            stack: error.stack,
            name: error.name
        });

        // Send meaningful error message
        const errorMessage = error.message || 'Failed to create prescription';
        res.status(500).json({
            message: 'Server error',
            error: errorMessage,
            details: process.env.NODE_ENV === 'development' ? error.stack : undefined
        });
    }
};

// @desc    Request lab test
// @route   POST /api/doctor/lab-request
// @access  Private/Doctor
exports.requestLabTest = async (req, res) => {
    try {
        const doctor = await Doctor.findOne({ userId: req.user._id });

        if (!doctor) {
            return res.status(404).json({ message: 'Doctor profile not found' });
        }

        const { patientId, testType, description } = req.body;

        const labTest = await LabTest.create({
            patientId,
            doctorId: doctor._id,
            testType,
            description
        });

        // Notify all laboratory users about new lab request
        const labUsers = await User.find({ role: 'laboratory', status: 'approved' }).select('_id').lean();
        const patient = await Patient.findById(patientId).select('fullName').lean();
        const patientName = patient?.fullName || 'Patient';
        for (const u of labUsers) {
            await Notification.create({
                userId: u._id,
                type: 'lab_request',
                title: 'New Lab Test Request',
                message: `Dr. ${doctor.fullName} requested ${testType} for ${patientName}.`,
                data: { labTestId: labTest._id }
            });
        }

        res.status(201).json(labTest);
    } catch (error) {
        console.error(error);
        res.status(500).json({ message: 'Server error' });
    }
};

// @desc    Get doctor workload analysis (AI)
// @route   GET /api/doctor/workload
// @access  Private/Doctor
exports.getWorkloadAnalysis = async (req, res) => {
    try {
        const doctor = await Doctor.findOne({ userId: req.user._id });
        if (!doctor) {
            return res.status(404).json({ message: 'Doctor profile not found' });
        }

        const { daysBack = 7 } = req.query;
        const workload = await aiService.getDoctorWorkloadAnalysis(doctor._id, parseInt(daysBack));
        res.json(workload);
    } catch (error) {
        console.error(error);
        res.status(500).json({ message: 'Server error' });
    }
};

/**
 * @desc    Get AI-generated clinical summary for a patient
 * @route   GET /api/doctor/patient/:id/summary
 * @access  Private/Doctor+Staff
 */
exports.getPatientClinicalSummary = async (req, res) => {
    try {
        const patientId = req.params.id;
        const patient = await Patient.findById(patientId);

        if (!patient) {
            return res.status(404).json({ message: 'Patient profile not found' });
        }

        const { memberId } = req.query;
        let memberFilter = {};
        if (memberId && memberId !== 'null') {
            memberFilter = { 'bookedForMember.memberId': memberId };
        } else if (memberId === 'null') {
            memberFilter = { 'bookedForMember.memberId': null };
        }

        const baseQuery = { patientId: patient._id, ...memberFilter };

        // Get past prescriptions (last 5)
        const prescriptions = await Prescription.find(baseQuery)
            .sort({ createdAt: -1 })
            .limit(5);

        // Get past lab tests (last 5 completed OR those with PDFs)
        const labTests = await LabTest.find({
            ...baseQuery,
            $or: [{ status: 'completed' }, { reportPDF: { $ne: null } }]
        })
            .sort({ updatedAt: -1 })
            .limit(10); // Check more to find PDFs

        // Get PDF Report Findings (latest 2 reports)
        const pdfReports = labTests.filter(lt => lt.reportPDF).slice(0, 2);
        let reportFindings = '';
        
        for (const report of pdfReports) {
            // Normalize path (handle both absolute and relative)
            let absolutePath = path.isAbsolute(report.reportPDF) 
                ? report.reportPDF 
                : path.resolve(process.cwd(), report.reportPDF);
            
            // Fallback if not found: try relative to __dirname (backward compatibility)
            if (!fs.existsSync(absolutePath)) {
                absolutePath = path.join(__dirname, '..', report.reportPDF);
            }

            console.log(`[Clinical Summary] Attempting to extract text from: ${absolutePath}`);
            const text = await extractTextFromPDF(absolutePath);
            if (text) {
                console.log(`[Clinical Summary] Successfully extracted ${text.length} chars from ${report.testName}`);
                reportFindings += `--- Report: ${report.testName} ---\n${text}\n\n`;
            } else {
                console.warn(`[Clinical Summary] Extraction returned empty for: ${report.testName}`);
            }
        }

        // Defensive mapping to ensure no crashes on missing fields
        const summaryParams = {
            patient,
            chronicDiseases: (patient.chronicDiseases || []).map(d => d.disease || 'Unknown'),
            allergies: (patient.allergies || []).map(a => a.allergen || 'Unknown'),
            prescriptions: (prescriptions || []).map(p => ({
                date: p.createdAt ? new Date(p.createdAt).toLocaleDateString() : 'Unknown',
                diagnosis: p.diagnosis || 'Not specified',
                medicines: (p.medicines || []).map(m => m.name).join(', ') || 'None'
            })),
            labResults: (labTests || []).map(lt => ({
                testName: lt.testName || 'Unknown',
                result: (lt.results || []).map(r => `${r.parameter}: ${r.value}${r.unit || ''}`).join(', ') || 'See report'
            })),
            reportFindings // Pass extracted PDF text
        };

        const summaryData = await geminiService.getPatientProfileSummary(summaryParams);
        res.json(summaryData);
    } catch (error) {
        console.error('getPatientClinicalSummary error details:', error);
        res.status(500).json({ 
            success: false, 
            message: 'Error generating patient summary',
            details: error.message 
        });
    }
};
